propeller:
  rawoutput-prefix: s3://my-s3-bucket/
  workers: 40
  gc-interval: 12h
  max-workflow-retries: 50
  leader-election:
    lock-config-map:
      name: propeller-leader
      namespace: flyte
    enabled: true
    lease-duration: 15s
    renew-deadline: 10s
    retry-period: 2s
