apiVersion: v1
kind: Service
metadata:
  name: flytepropeller
  namespace: flyte
  annotations:
    cloud.google.com/load-balancer-type: Internal
spec:
  type: LoadBalancer
  selector:
    app: flytepropeller
  ports:
  - name: http-metrics
    protocol: TCP
    port: 10254
