apiVersion: v1
kind: ServiceAccount
metadata:
  name: flytepropeller
  namespace: flyte
  annotations:
    # TODO the role to use
    eks.amazonaws.com/role-arn: "arn:aws:iam::111222333456:role/flyte-operator"
