propeller:
  rawoutput-prefix: s3://my-s3-bucket/
  leader-election:
    lock-config-map:
      name: propeller-leader
      namespace: flyte
    enabled: true
    lease-duration: 15s
    renew-deadline: 10s
    retry-period: 2s
