database:
  port: 5432
  username: flyte
  # TODO Change this to match aurora or rds postgres endpoint
  host: flyteadmin-cluster.cluster-456123e6ivib.us-west-2.rds.amazonaws.com
  dbname: flyte
  passwordPath: /etc/db/pass.txt
